version: '3.3'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node-api
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - database
    networks:
      - mern-network
      - monitoring
    env_file:
      - ./backend/config/config.env

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react-ui
    ports:
      - "3030:3000"
    stdin_open: true
    tty: true
    depends_on:
      - backend
    networks:
      - mern-network
      - monitoring   

  database:
    image: mongo
    container_name: mongo-db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - /home/devops-ubnt/project-backup/mern-backup:/data/db
    networks:
      - mern-network
      - monitoring

networks:
  mern-network:
    driver: bridge
  monitoring:
    driver: bridge

